# Generated by Django 6.0.4 on 2026-07-13 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespondentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('NS', 'Prefer not to say')], max_length=5)),
                ('age_group', models.CharField(blank=True, choices=[('under18', 'Under 18'), ('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45+', '45+')], max_length=10)),
                ('avatar', models.CharField(default='default', max_length=50)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
