# Generated by Django 6.0.4 on 2026-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating_max',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_style',
            field=models.CharField(blank=True, choices=[('stars', 'Stars'), ('numeric', 'Numeric'), ('likert', 'Likert')], default='stars', max_length=10),
        ),
    ]
