# Generated by Django 6.0.4 on 2026-05-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_rating_max_question_rating_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='section_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='btn_color',
            field=models.CharField(default='#14140f', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='btn_font_size',
            field=models.CharField(default='14px', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='btn_padding',
            field=models.CharField(default='10px 22px', max_length=30),
        ),
        migrations.AddField(
            model_name='survey',
            name='btn_radius',
            field=models.CharField(default='6', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='header_image_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
