# Generated by Django 6.0.4 on 2026-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_section_num_question_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
