# Generated by Django 6.0.4 on 2026-05-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
