# Generated by Django 6.0.4 on 2026-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='header_font',
            field=models.CharField(default="'Instrument Serif',serif", max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='q_font',
            field=models.CharField(default="'Inter',sans-serif", max_length=50),
        ),
    ]
